#!/bin/bash

# Set the name of the private key
private_key_name="school"

# Set the number of bits for the key
key_bits=4096

# Set the passphrase for the key
passphrase="betty"

# Generate the key pair
ssh-keygen -t rsa -b $key_bits -N $passphrase -f $private_key_name

# Print the key information
echo "Generating public/private rsa key pair."
echo "Your identification has been saved in $private_key_name."
echo "Your public key has been saved in $private_key_name.pub."
echo "The key fingerprint is:"
ssh-keygen -l -f $private_key_name.pub
echo "The key's randomart image is:"
ssh-keygen -lv -f $private_key_name.pub

# List the files in the current directory
ls

